[package]
name = "rsjson"
version = "0.1.0"
authors = ["ryzeon-dev"]
description = "Json file parser library"
edition = "2021"
license = "AGPL-3.0-or-later"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
