[package]
name = "rsjson"
version = "0.3.1"
authors = ["ryzeon-dev"]
description = "Json parser library"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ryzeon-dev/rsjson"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
